# Generated by Django 3.0.8 on 2020-07-12 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='persons/', verbose_name='Фотография')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Отчество')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('bio', models.TextField(verbose_name='Краткая биография')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='Голоса')),
            ],
            options={
                'verbose_name': 'Кандитат',
                'verbose_name_plural': 'Кандидаты',
            },
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Голосование')),
                ('name', models.CharField(max_length=200, verbose_name='Название голосования')),
                ('start', models.DateTimeField(verbose_name='Дата начала')),
                ('finish', models.DateTimeField(verbose_name='Дата завершения')),
                ('max_count_votes', models.PositiveIntegerField(default=0, verbose_name='Максимальное число голосов для победы')),
                ('active', models.BooleanField(verbose_name='Статус')),
                ('persons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Persons', verbose_name='Кандидаты')),
            ],
            options={
                'verbose_name': 'Голосование',
                'verbose_name_plural': 'Голосования',
            },
        ),
    ]
