# Generated by Django 3.0.8 on 2020-07-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_polls_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='url',
            field=models.SlugField(default='url', max_length=160, unique=True),
        ),
    ]
