# Generated by Django 3.0.8 on 2020-07-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200712_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persons',
            options={'ordering': ['-votes'], 'verbose_name': 'Кандитат', 'verbose_name_plural': 'Кандидаты'},
        ),
    ]
